on:
  push:
    branches:
      - master
name: Production Deploy
jobs:
  web-deploy:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: FTP-Deploy-Action
        uses: actions/checkout@v2.1.0

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.sepatil.in
          username: techblog@sepatil.in
          password: ${{ secrets.FTP_TECHBLOG_PASSWORD }}
